<?php
/**
 * @file
 * Panels Omega 4 Col 4-4-4 Stacked
 *
 */

$plugin = array(
    'title' => t('3 Col. 4-4-4 - Content on left'),
    'category' => t('Insights Layout'),
    'icon' => 'omega_3col_4_4_4_content_left_stacked.png',
    'theme' => 'panels_omega_3col_4_4_4_stacked',
    'admin css' => '../omega_panels_admin_12.css',
    'regions' => array(
      'top' => t('Top'),
      'left' => t('Left side'),
      'middle' => t('Middle column'),
      'right' => t('Right side'),
      'bottom' => t('Bottom'),
    ),
  );
