<?php
/**
 * @file
 * Panels Omega 2 Col 5-7 Stacked
 *
 */

$plugin = array(
  'title' => t('2 Col. 5-7'),
  'category' => t('Insights Layout'),
  'icon' => 'omega_2col_5_7_stacked.png',
  'theme' => 'panels_omega_2col_5_7_stacked',
  'admin css' => '../omega_panels_admin_12.css',
  'regions' => array(
    'top' => t('Top'),
    'left' => t('Left'),
    'right' => t('Right'),
    'bottom' => t('Bottom'),
  ),
);
