<?php
/**
 * @file
 * Panels Omega 3 Col 3-6-3 Stacked
 *
 */

$plugin = array(
    'title' => t('3 Col. 3-6-3'),
    'category' => t('Insights Layout'),
    'icon' => 'omega_3col_3_6_3_stacked.png',
    'theme' => 'panels_omega_3col_3_6_3_stacked',
    'admin css' => '../omega_panels_admin_12.css',
    'regions' => array(
      'top' => t('Top'),
      'left' => t('Left side'),
      'middle' => t('Middle column'),
      'right' => t('Right side'),
      'bottom' => t('Bottom'),
    ),
  );
